### ISSUE TITLE
Invalid unicode output

### ISSUE THREAD

**Issue by donat-b** [monky-hs/monky#28]
```
[[{"full_text": " 369B   27B"},{"full_text": "🐏 ", "separator": false, "separator_block_width": 1},{"full_text": "12.2Gi"}
```

uniname:

```
      145        145  01F40F   F0 9F 90 8F    🐏      Character in undefined range
```

What might be the reason? Do I need some library?

To be clear, it should have been the bar.

**Comment by Ongy** [comment]
This is a problem with some versions of ghc. They try to validate unicode chars in a weird way.
What ghc version do you have?

**Comment by Ongy** [comment]
Ah it's not a compile error, sorry I misread.
What's uniname? I don't know it.

**Comment by donat-b** [comment]
Uniname is a part of unicode utilities, which provides info about unicode characters.
I just used it to demonstrate it's not printing valid characters, so it's not problem with fonts.

**Comment by donat-b** [comment]
Which GHC version is known to work?

**Comment by Ongy** [comment]
It's not a ghc issue. I misread.

Monky actually outputs `F0 9F 90 8F` which is defined. See http://www.fileformat.info/info/unicode/char/1f40f/index.htm.
If the uniname you are using is from [here](http://billposer.org/Software/unidesc.html) the problem is, that it's horribly outdated. It was last updated 2009. The 🐏 character has been added in 2010 (see first link).

If the missing character breaks things, the easiest way to get rid of it is using `Monky.Examples.Modify`:

> getModifyHandle (\(x:xs) -> xs) getMemoryHandle

**Comment by donat-b** [comment]
Oy vey.
Didn't expect that. :smile: 
Installed Roboto fonts and everything is looking great now.
You should probably mention somewhere that the Unicode output requires modern fonts.
